version: '3.8'

services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SCORING_SERVICE_URL=http://scoring-engine:8001
    depends_on:
      - scoring-engine
    volumes:
      - .:/app
      - /app/node_modules

  scoring-engine:
    build: ./services/scoring-engine
    ports:
      - "8001:8001"
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./services/scoring-engine:/app
